minVersion: "0.21.0"
github:
  owner: getsentry
  repo: responses
changelog: CHANGES
targets:
  - name: pypi
  - name: github
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
requireNames:
  - /^responses-.+-py3-none-any.whl$/
  - /^responses-.+.tar.gz$/
