repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      args: [--line-length=88, --safe]
      python_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
    - id: flake8
      log_file: '.artifacts/flake8.log'
    - id: requirements-txt-fixer
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ['--force-single-line-imports', '--profile', 'black']
      - id: isort
        name: isort (pyi)
        types: [ pyi ]
        args: ['--force-single-line-imports', '--profile', 'black']
