name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install-pre-commit
        make install-deps

    - name: Run pre-commit
      run: |
        pre-commit run -a -v

    - name: Run mypy
      run: |
        mypy --config-file=./mypy.ini -p responses

    - name: Run mypy (namespace packages)
      run: |
        # see https://github.com/getsentry/responses/issues/556
        mypy --config-file=./mypy.ini --namespace-packages -p responses

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        requests-version: ['"requests>=2.0,<3.0"']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ${{ matrix.requests-version }}
        make install-deps

    - name: Run Pytest
      run: |
        # Run test
        pytest . --asyncio-mode=auto --cov-report term-missing --cov-report xml --cov responses

    - name: Code Coverage Report
      if: success()
      uses: codecov/codecov-action@v3
